### ISSUE TITLE
Move sprout-rubymine to the attic

### ISSUE THREAD

**Issue by hiremaga** [pivotal-sprout/sprout-rubymine#5]
In `~/workspace/sprout-attic` run:

```
git remote add sprout-rubymine git@github.com:pivotal-sprout/sprout-rubymine.git
git subtree split -P sprout-rubymine --branch sprout-rubymine
git push sprout-rubymine sprout-rubymine:master
```

Then delete the sprout-rubymine repository.

**Comment by wendorf** [comment]
I suggest creating a pivotal-sprout-attic org rather than using the pivotal-sprout/sprout-attic repo. One of the more difficult parts of going through the cookbooks has been losing history as recipes moved between repos. Even if the recipes are deprecated, it would be nice to keep the git history.

**Comment by hiremaga** [comment]
A subtree split solves the problem of losing history, in fact this is what we did for [pivotal_workstation](https://github.com/pivotal-sprout/sprout-attic/commits/master/pivotal_workstation). We used a similar approach when reorganizing pivotal_workstation into sprout, it was pretty easy.

Steps from the [tracker story](https://www.pivotaltracker.com/story/show/70019010) to move pivotal_workstation into sprout-attic:

```
git remote add ${COOKBOOK} git@github.com:pivotal-sprout/${COOKBOOK}.git
git subtree split -P ${COOKBOOK} --branch ${COOKBOOK}
git push ${COOKBOOK} ${COOKBOOK}:master
```
I prefer the current repo over a new org since it keeps all things sprout searchable under the one org. I like that it makes using these old cookbooks less convenient.

**Comment by wendorf** [comment]
Sounds reasonable; I actually had no clue about subtrees in git. Submitted [this PR](https://github.com/pivotal-sprout/sprout-attic/pull/1) to move it to the attic. Once merged, this repo can be removed.

For posterity, I ended up doing this:

```
git remote add sprout-rubymine https://github.com/pivotal-sprout/sprout-rubymine
git subtree add --prefix sprout-rubymine sprout-rubymine master
```

**Comment by wendorf** [comment]
Sprout-Rubymine has been fully moved to the attic and deprecated.
